[package]
name = "keter_duty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.58"
clap = { version = "3.2.8", features =[ "derive" ] }
include_dir = "0.7.2"
lazy_static = "1.4.0"
tera = "1.15.0"
whoami = "1.2.1"
